version: '3.7'

services:

  smart_administrator_app:
    container_name: smart_administrator_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports: [3000:3000]
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true 